# Generated by Django 6.1 on 2026-08-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_users', '0002_user_avatar_url_user_dark_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='display_name',
            new_name='name',
        ),
    ]
